#!/bin/bash
#SBATCH --job-name=gsamixse
#SBATCH --account=p697
#SBATCH --time=36:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=8000M  # 502 GB available => 502*1024/64 = 8032 MB max per core
#SBATCH --cpus-per-task=32    # remember to update --threads argument below!
#SBATCH --chdir slurm

export THREADS=16

source /cluster/bin/jobsetup

test $SCRATCH && module load singularity/3.7.1 

export SUMSTATS_FOLDER=/ess/p697/cluster/users/ofrei/2023_02_06_GSA_MiXeR_natgen_revisions/sumstats_v3p1
export SUMSTATS_FILE=$1

export OUT_FOLDER=/ess/p697/cluster/users/ofrei/2023_02_06_GSA_MiXeR_natgen_revisions/out50

export REFERENCE_FOLDER=/ess/p697/data/durable/s3-api/github/precimed/mixer_private_docker/reference
export ANNOT_VERSION=annot_10mar2023

export SINGULARITY_BIND=
export MIXER_SIF=/ess/p697/data/durable/s3-api/github/norment/ofrei_repo/2023_03_27/mixer.sif
#md5sum ${MIXER_SIF}

#export MIXER_PY="singularity exec --home $PWD:/home --bind /ess/p697:/ess/p697 ${MIXER_SIF} python /tools/mixer/precimed/mixer.py"
export PYTHON="singularity exec --home $PWD:/home --bind /ess/p697:/ess/p697 ${MIXER_SIF} python"
#export JUPYTER="singularity exec --home $PWD:/home --bind /ess/p697:/ess/p697 ${MIXER_SIF} jupyter notebook --port 8989"
#export MIXER_PY="singularity exec --home $PWD:/home --bind /ess/p697:/ess/p697 ${MIXER_SIF} python /ess/p697/data/durable/s3-api/github/precimed/mixer_private/precimed/mixer.py"
export MIXER_PY="singularity exec --home $PWD:/home --bind /ess/p697:/ess/p697 ${MIXER_SIF} python /ess/p697/cluster/users/ofrei/2023_02_06_GSA_MiXeR_natgen_revisions/precimed/mixer.py"

export EXTRA_FLAGS="--seed 1000 --exclude-ranges MHC --hardprune-r2 0.6 --threads ${THREADS} "
export LOADLIB_FILE=/ess/p697/cluster/projects/moba_qc_imputation/resources/HRC/plink/tsd_libfile_hrc_chr@.bin

# just to test if commands run, add the following:
#export EXTRA_JUNK="--chr2use 21-22 --adam-epoch 3 3 --adam-step 0.064 0.032"
export EXTRA_JUNK=

# ${MIXER_PY} split_sumstats --trait1-file ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.sumstats.gz --out ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.chr@.sumstats.gz

export ANNOT_FILE="${REFERENCE_FOLDER}/hrc_EUR_qc/baseline_v2.2_hrc_chr@_EUR_qc.annot.gz"

${MIXER_PY} plsa --gsa-base \
        --trait1-file ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.chr@.sumstats.gz \
        --out ${OUT_FOLDER}/${SUMSTATS_FILE}_base \
        --bim-file ${REFERENCE_FOLDER}/hrc_EUR_qc/hrc_chr@_EUR_qc.bim \
        --ld-file ${REFERENCE_FOLDER}/hrc_EUR_qc/hrc_chr@_EUR_qc.run1.ld \
        --use-complete-tag-indices --loadlib-file ${LOADLIB_FILE} \
        --go-file ${REFERENCE_FOLDER}/gsa-mixer-baseline-${ANNOT_VERSION}.csv \
        --annot-file ${ANNOT_FILE} \
        --make-snps-file ${EXTRA_FLAGS} ${EXTRA_JUNK}

${MIXER_PY} plsa --gsa-full \
        --trait1-file ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.chr@.sumstats.gz \
        --out ${OUT_FOLDER}/${SUMSTATS_FILE}_full \
        --bim-file ${REFERENCE_FOLDER}/hrc_EUR_qc/hrc_chr@_EUR_qc.bim \
        --ld-file ${REFERENCE_FOLDER}/hrc_EUR_qc/hrc_chr@_EUR_qc.run1.ld \
        --use-complete-tag-indices --loadlib-file ${LOADLIB_FILE} \
        --go-file ${REFERENCE_FOLDER}/gsa-mixer-gene-${ANNOT_VERSION}.csv \
        --go-file-test ${REFERENCE_FOLDER}/gsa-mixer-hybridLOO-${ANNOT_VERSION}.csv \
        --annot-file ${ANNOT_FILE} \
        --load-params-file ${OUT_FOLDER}/${SUMSTATS_FILE}_base.json \
        --make-snps-file ${EXTRA_FLAGS} ${EXTRA_JUNK}
