#!/bin/bash
#SBATCH --job-name=magma
#SBATCH --account=p697
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=8000M  # 502 GB available => 502*1024/64 = 8032 MB max per core
#SBATCH --cpus-per-task=4
#SBATCH --chdir slurm

source /cluster/bin/jobsetup

test $SCRATCH && module load singularity/3.7.1 

export OUT_FOLDER=/ess/p697/cluster/users/ofrei/2023_02_06_GSA_MiXeR_natgen_revisions/out17
export SUMSTATS_FOLDER=/ess/p697/cluster/users/ofrei/2023_02_06_GSA_MiXeR_natgen_revisions/sumstats_v3p1
export SUMSTATS_FILE=$1

export REFERENCE_FOLDER=/ess/p697/data/durable/s3-api/github/precimed/mixer_private_docker/reference
export ANNOT_VERSION=annot_10mar2023

export SINGULARITY_BIND=
export MIXER_SIF=/ess/p697/data/durable/s3-api/github/norment/ofrei_repo/2023_03_27/mixer.sif
#md5sum ${MIXER_SIF}

export MAGMA="singularity exec --home $PWD:/home --bind /ess/p697:/ess/p697 ${MIXER_SIF} magma"
export MAGMA_BFILE=/ess/p697/cluster/projects/moba_qc_imputation/resources/HRC/plink/hrc_EUR_qc_keep1k
export MAGMA_GENE_LOC=${REFERENCE_FOLDER}/magma-gene-${ANNOT_VERSION}.csv
export MAGMA_SET_ANNOT=${REFERENCE_FOLDER}/magma-geneset-${ANNOT_VERSION}.csv
export OUT=${OUT_FOLDER}/${SUMSTATS_FILE}

#zcat  ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.sumstats.gz >  ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.sumstats

$MAGMA --snp-loc ${MAGMA_BFILE}.bim \
       --gene-loc ${MAGMA_GENE_LOC} \
       --out $OUT.magma.step1 \
       --annotate window=10 
$MAGMA --pval ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.sumstats snp-id=RSID pval=P ncol=N \
       --bfile ${MAGMA_BFILE} \
       --gene-annot $OUT.magma.step1.genes.annot \
       --out $OUT.magma.step2
$MAGMA --gene-results $OUT.magma.step2.genes.raw \
       --set-annot ${MAGMA_SET_ANNOT} \
       --out $OUT.magma
 
