name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/gsa-mixer            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}} 
          labels: |
            org.opencontainers.image.source=https://github.com/precimed/gsa-mixer
            org.opencontainers.image.description=GSA-MiXeR
            org.opencontainers.image.licenses=GPL-3.0
            org.opencontainers.image.authors=https://github.com/precimed/gsa-mixer/graphs/contributors
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file:
            ./Dockerfile
          platforms: linux/amd64

  build-apptainer-container:
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build Apptainer Container
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4
      - name: Docker meta 
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/gsa-mixer            
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Apptainer container
        run: |
          tags="${{ steps.meta.outputs.tags }}"
          csv_tags=$(printf "%s\n" "$tags" | awk -F: 'NR==1{printf "%s,", $0; next} {printf "%s,", $NF}' | sed 's/,$//')
          IFS= read -r first_tag <<EOF
          $tags
          EOF
          push_tags="$(printf $csv_tags | sed -e "s/gsa-mixer/gsa-mixer_sif/g")"
          echo ${{ secrets.GITHUB_TOKEN }} | oras login --username ${{ github.repository_owner }} --password-stdin ghcr.io
          docker pull kaczmarj/apptainer:latest
          docker run --rm --privileged -v $(pwd):/work kaczmarj/apptainer build gsa-mixer.sif docker://"$first_tag"
          oras push "$push_tags" gsa-mixer.sif
          rm gsa-mixer.sif
        shell: sh
